on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build on Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - run: npm ci --no-optional --force
      - run: npm run build -- ngx-kjua --configuration=production
      # Add all documentation files to the build
      - run: cp *.md dist/ngx-kjua/
      # Copy all assets to the build
      - run: cp --parents src/assets/* dist/ngx-kjua
      - run: cp LICENSE dist/ngx-kjua/
      - name: Test on ${{ inputs.node-version }}
        run: npm run test
      - uses: actions/upload-artifact@v3
        with:
          name: ngx-kjua
          path: dist/ngx-kjua/
