# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
name: Node.js CI

on: [push]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      node-version: 22
