# Reusable npm publish / release job
on:
  workflow_call:
    inputs:
      registry-url:
        required: true
        type: string
      node-version:
        required: true
        type: number
      release-tag:
        required: false
        type: string
    secrets:
      npm-token:
        required: true

jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ngx-kjua
          path: dist/ngx-kjua/
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}
      - run: npm ci --no-optional --force
      - run: npm publish --access public ${{ inputs.release-tag }}
        working-directory: dist/ngx-kjua/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
